name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Download ngrok
      run: curl -fsSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken $ENV:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Allow Remote Login (**Security Risk**!)
      run: sysctl -w UserDir=/Users/Shared  #**Potentially Insecure**
    - run: launchctl enable system.screensharing  #**Potentially Insecure**
    - name: Create Tunnel
      run: ./ngrok tcp 3389
